MODEL:
  TYPE: litevla_for_ab
  NAME: litevla_n_no_attn
  LITEVLA:
    DIMS: [48, 96, 192, 384]
    DEPTHS: [2, 2, 11, 3]
    BLOCK_TYPES: ['GAB', 'GAB', 'VLA', 'VLA']
    STEM_KERNEL: 5
    DS_EXP: 4
    DS_KERNEL: 3
    DS_FUSE: 'ff--'
    ACT: 'silu'
    DWC_KERNEL: 5
    ATTN_RATIO: 0.125
    ATTN_KERNEL: 'elu1'
    ATTN_NORM: 'mrms'
    MLP_RATIO: 3
    HEAD_NORM: 'mrms'

    ##################
    ABLATION: "no_attn"

TRAIN:
  WARMUP_EPOCHS: 10
