MODEL:
  TYPE: litevla_for_ab
  NAME: litevla_n_0_mlp2
  LITEVLA:
    DIMS: [48, 96, 192, 384]
    DEPTHS: [2, 2, 14, 6]  ##################### 2,2,11,3 -> 2,2,14,6
    BLOCK_TYPES: ['GAB', 'GAB', 'VLA', 'VLA']
    STEM_KERNEL: 5
    DS_EXP: 4
    DS_KERNEL: 3
    DS_FUSE: 'ff--'
    ACT: 'silu'
    DWC_KERNEL: 5
    ATTN_RATIO: 0.125
    ATTN_KERNEL: 'elu1'
    ATTN_NORM: 'mrms'
    MLP_RATIO: 2  ###################### 3 -> 2
    HEAD_NORM: 'mrms'

    ##################
    ABLATION: "xxx"

TRAIN:
  WARMUP_EPOCHS: 10
