MODEL:
  TYPE: litevla
  NAME: litevla_m
  # DROP_PATH_RATE: 0.1
  LITEVLA:
    DIMS: [56, 112, 224, 448]
    DEPTHS: [2, 2, 11, 3]
    BLOCK_TYPES: ['GAB', 'GAB', 'VLA', 'VLA']
    STEM_KERNEL: 5
    DS_EXP: 4
    DS_KERNEL: 3
    DS_FUSE: 'f---'
    ACT: 'silu'
    DWC_KERNEL: 5
    ATTN_RATIO: 0.125
    ATTN_KERNEL: 'elu1'
    ATTN_NORM: 'mrms'
    MLP_RATIO: 3
    HEAD_NORM: 'mrms'

TRAIN:
  WARMUP_EPOCHS: 10

# medium 
# TODO [HSC]: retest performance for [2,2,11,3]
# 224: 1.49ms / 512: 4.86ms (iPhone 14)
# 224: x.xxms / 512: x.xxms (iPhone 14 pro)