MODEL:
  TYPE: litevla
  NAME: litevla_t
  LITEVLA:
    DIMS: [32, 64, 128, 256]
    DEPTHS: [1, 2, 7, 2]
    BLOCK_TYPES: ['GAB', 'GAB', 'GAB', 'VLA']
    STEM_KERNEL: 5
    DS_EXP: 4
    DS_KERNEL: 3
    DS_FUSE: 'ffff'
    ACT: 'silu'
    DWC_KERNEL: 5
    AGG_RATIO: 1.
    ATTN_RATIO: 0.125
    ATTN_KERNEL: 'elu1'
    ATTN_NORM: 'mrms'
    MLP_RATIO: 3
    HEAD_NORM: 'mrms'

TRAIN:
  WARMUP_EPOCHS: 10

# tiny
# 0.62ms (iPhone 14)